services:
  - type: web
    name: ecom-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 20